INSERT INTO mykeyspace.monkeyspecies (species, average_size, common_name, population) VALUES ('Macaca fascicularis', 5, 'Crab-eating Macaque', 5000000);
INSERT INTO mykeyspace.monkeyspecies (species, average_size, common_name, population) VALUES ('Gorilla beringei', 160, 'Mountain Gorilla', 1063);
INSERT INTO mykeyspace.monkeyspecies (species, average_size, common_name, population) VALUES ('Pan troglodytes', 70, 'Chimpanzee', 170000);
INSERT INTO mykeyspace.monkeyspecies (species, average_size, common_name, population) VALUES ('Alouatta caraya', 7, 'Black Howler Monkey', 15000);
INSERT INTO mykeyspace.monkeyspecies (species, average_size, common_name, population) VALUES ('Cebus capucinus', 3, 'White-faced Capuchin', 100000);
INSERT INTO mykeyspace.monkeyspecies (species, average_size, common_name, population) VALUES ('Saguinus niger', 500, 'Black tamarin', 10000);
INSERT INTO mykeyspace.monkeyspecies (species, average_size, common_name, population) VALUES ('Theropithecus gelada', 18, 'Gelada', 200000);
INSERT INTO mykeyspace.monkeyspecies (species, average_size, common_name, population) VALUES ('Mandrillus sphinx', 24, 'Mandrill', 3000);
